model_name: "llama-3.1-8b"
model_path: "/models--llama-3.1/hf/8B-Instruct"
data_path: "/data/{culture}_data.jsonl"
output_dir: "/outputs/responses/"
cache_dir: ""
culture: Chinese
strategy: profile
generate_cfg:
  temperature: 0.7
  max_new_tokens: 1000
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 
hydra:  
  output_subdir: null  
  run:  
    dir: . 
